### ISSUE TITLE
How can I identify if the plugin was installed

### ISSUE THREAD

**Issue by johnidm** [contentools/wp-contentools#1]
We can to use a custom header to identify if the plugin was installed

The snippet code is an example:
```
add_action( 'send_headers', 'add_header_xua' );
function add_header_xua() {
	@header( 'X-UA-Compatible: IE=edge,chrome=1' );
}
```

The Angular snniped code is: 
```
$http.get('http://johnidouglas.com/').then(function(response) {
  var installed = response.headers('WP-Contentools));
});
```

https://codex.wordpress.org/Plugin_API/Action_Reference/send_headers

If var `installed` is `false`, we can to enable a button with this action `http://johnidouglas.com/wp-admin/update.php?action=install-plugin&plugin=wp-contentools&_wpnonce=73d25b117f`

**Comment by Lobosque** [comment]
Try using HEAD instead GET and check if it works.
This way you use less bandwidth by downloading only the headers and not the actual content :sunglasses:

**Comment by johnidm** [comment]
Done
